### ISSUE TITLE
What is this repository's license?

### ISSUE THREAD

**Issue by monokrome** [jwilder/docker-discover#13]
I started [a fork for my own personal cloud of servers][frk], but am worried that there isn't a license. Would it be reasonable to request that a license be added so that people whom may be unsure can use this as well?

Thanks! This is a neat project :)

@jwilder 

[frk]: https://www.github.com/monokrome/platform-discovery

**Comment by jwilder** [comment]
Done. MIT

**Comment by monokrome** [comment]
Thanks, @jwilder!
