### ISSUE TITLE
Error in starting

### ISSUE THREAD

**Issue by alessioguglielmo** [jwilder/docker-discover#4]
docker run -d --net host --name docker-discover -e ETCD_HOST=192.168.56.102:4001 -p 1936:1936 -t jwilder/docker-discover

docker logs docker-discover

Error: 'Key not found : /backends'
Error: 'Key not found : /backends'
Error: 'Key not found : /backends'
Error: 'Key not found : /backends'

service on 1936 is unreacheable. Also whoami servers is unreacheable. 
If I try to connect directly to a single whoami serv it works fine.

**Comment by ghost** [comment]
It works with `--privileged`
